MAX_LENGTH_NAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_COLOR = 7
MIN_TIME_MESSAGE = 'Минимальное время приготовления 1 минута'
MAX_TIME_MESSAGE = 'Максимальное время приготовления  1 день (1440 минут)'
MIN_INGR_MESSAGE = 'Выберxете минимум 1 ингредиент'
MAX_INGR_MESSAGE = 'Максимальный вес ингредиента - 3000 г'
MIN_AMOUNT_TIME_OR_INGR = 1
MAX_AMOUNT_TIME = 1440
MAX_AMOUNT_INGR = 3000
NOT_AMOUNT_MESSAGE = 'Количество ингридиентов меньше 1'
NOT_REPEAT_MESSAGE = 'Ингридиенты не должны повторяться!'
MIN_AMOUNT_MESSAGE = 'Количество ингредиентов должно быть больше 0!'
UNIQUE_TAG_MESSAGE = 'Тег должнен быть уникальным!'
MIN_TAG_MESSAGE = 'Необходимо указать минимум бы один тег!'
VALIDATE_NAME_MESSAGE = 'Не может состоять только из цифр или символов'
ERR_SUB_YOUSELF = 'Нельзя подписаться на себя!'
ERR_ALREADY_SUB = 'Вы уже подписаны'
ERR_SUB_ALL = 'Подписаться невозможно'
ERR_NOT_FOUND = 'Данные для входа не найдены'
ERR_ALREADY_RECIPE = 'Рецепт уже добавлен!'
ERR_DEL_RECIPE = 'Рецепт уже удален!'
